---
- name: create a stack, pass in the template via an URL
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ aws_region }}"
    disable_rollback: false
    template_url: "{{ template_url }}"
    template_parameters:
      EnvironmentName: "{{ environment_name }}"
      VpcCIDR: "{{ vpc_cidr }}"
      PublicSubnet1CIDR: "{{ public_subnet_1_cidr }}"
      PublicSubnet2CIDR: "{{ public_subnet_2_cidr }}"
      PrivateSubnet1CIDR: "{{ private_subnet_1_cidr }}"
      PrivateSubnet2CIDR: "{{ private_subnet_2_cidr }}"
    tags:
      Stack: "{{ stack_name }}"

- name: get facts about the newly created cfn network stack
  cloudformation_facts:
    stack_name: "ansible-cfn-demo-network"
  register: cfn_network_stack_facts

- name: show the cfn network stack outputs
  debug:
    msg: "{{ cfn_network_stack_facts.ansible_facts.cloudformation['ansible-cfn-demo-network'].stack_outputs }}"
