---
# tasks file for cf

# https://docs.ansible.com/ansible/latest/modules/cloudformation_module.html
- name: delete a stack
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: absent
    region: "{{ aws_region }}"
