version: 0.2

env:
  variables:
    TAG_ENV: "development"
  parameter-store:
    ANSIBLE_PRIVATE_KEY: "/anisble_demo/ansible_private_key"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade -r requirements.txt -q
      - mkdir -p ~/.ssh
      - echo "$ANSIBLE_PRIVATE_KEY" > ~/.ssh/ansible
      - chmod 600 ~/.ssh/ansible
  build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml playbooks/20_cfn_compute.yml --tags create -vvv