version: 0.2

env:
  variables:
     ssh_location: "0.0.0.0/0"
  parameter-store:
     ansible_private_key: "ansible_private_key"
  #git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - mkdir -p ~/.ssh
      - echo "$ansible_private_key" > ~/.ssh/ansible
      - chmod 600 ~/.ssh/ansible
      - ls -alh ~/.ssh
      - pip3 install --upgrade -r requirements.txt --quiet
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - ansible-playbook --inventory inventories/aws_ec2.yml playbooks/10_cf_config.yml --tags create -vvvv
      # - sleep 300 # total hack to wait for ec2 instances to pass all status checks...
      - ansible-inventory -i inventories/aws_ec2.yml --graph
      - ansible-playbook --inventory inventories/aws_ec2.yml playbooks/20_webserver_config.yml -vvvv
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths