version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt -q
  pre_build:
    commands:
      - ansible-inventory -i inventories/aws_ec2.yml --graph
  build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml playbooks/40_tests.yml
  post_build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml roles/cfn_compute/tests/test.yml
      - ansible-playbook -i inventories/aws_ec2.yml roles/test_alb_webservers/tests/test.yml