version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install --upgrade -r requirements.txt --quiet
  pre_build:
    commands:
      # - command
      # - command
  build:
    commands:
      - ansible-playbook --inventory inventories/aws_ec2.yml site.yml --tags create -vvv
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths