version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade -r requirements.txt
  build:
    commands:
      - ansible-playbook --inventory inventories/aws_ec2.yml playbooks/10_cf_network.yml --tags create -vvv
