---
- name: create a stack, pass in the template via an URL
  vars:
    network_output: "cloudformation['ansible-cfn-demo-network'].stack_outputs"
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ aws_region }}"
    disable_rollback: false
    template_url: "{{ template_url }}"
    template_parameters:
      VpcId: "{{ network_output.VPC }}"
      Subnets: "{{ network_output.PublicSubnets }}"
      InstanceType: "{{ instance_type }}"
      KeyName: "{{ key_name }}"
      SSHLocation: "{{ ssh_location }}"
      TagName: "{{ tag_name }}"
      TagGroup: "{{ tag_group }}"
      TagEnv: "{{ lookup('env','TAG_ENV') }}"
    tags:
      Stack: "{{ stack_name }}"