---
- name: get facts about the newly created cfn network stack
  cloudformation_facts:
    stack_name: "ansible-cfn-demo-network"
  register: cfn_network_stack_facts

- name: create a stack, pass in the template via an URL
  vars:
    network_output: "{{ cfn_network_stack_facts.ansible_facts.cloudformation['ansible-cfn-demo-network'].stack_outputs }}"
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ aws_region }}"
    disable_rollback: false
    template_url: "{{ lookup('env','TEMPLATE_URL') }}"
    template_parameters:
      VpcId: "{{ network_output.VPC }}"
      Subnets: "{{ network_output.PublicSubnets }}"
      InstanceType: "{{ instance_type }}"
      KeyName: "{{ key_name }}"
      SSHLocation: "{{ ssh_location }}"
      TagName: "{{ tag_name }}"
      TagGroup: "{{ tag_group }}"
      TagEnv: "{{ lookup('env','ENVIRONMENT_NAME') }}"
    tags:
      Stack: "{{ stack_name }}"