version: 0.2

env:
  variables:
    TEMPLATE_URL: "https://s3.amazonaws.com/gaystafford_cloud_formation/cf_demo/network-stack.template"
    ENVIRONMENT_NAME: "ansible-cfn-demo"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt -q
  build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml playbooks/10_cfn_network.yml --tags create -vvv
  post_build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml roles/cfn_network/tests/test.yml